defaults:
  - 
    scope:
      path: ""
    values:
      layout: base
      title: Twig Site
      description: I make video games.
  -
    scope:
      path: kramer
    values:
      layout: kramer-page
      title: Kramer County
      description: Resources for a high lethality sitcom role-playing game.